version: "3"
services:
  app:
    build: .
    depends_on:
      - db

    environment:
      DATABASE_URL:
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5022:5000"
    command: npm run server
    volumes:
      - .:/app/

  db:
    image: postgres:latest
    ports:
      - "54982:3286"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: asicip_app

